# Generated by Django 5.2.3 on 2025-06-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_libro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='enlace',
            field=models.URLField(blank=True, help_text='Enlace a más información sobre el libro'),
        ),
    ]
