# Generated by Django 5.2.3 on 2025-06-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_libro_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Suba una imagen de la portada del libro', null=True, upload_to='libros/'),
        ),
    ]
